import Head from "next/head";
import Post from './components/Posts/Post.js';
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Posts</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>My Posts</h1>

        <ul className={styles.posts}>
          <li>
            <Post content="hey i am new list" date="3/2/2021" />
          </li>
          <li>
            <Post
              content="hello all i am working on figma trying to design website that
              shows all of my tweets!" date="3/2/2021 "/>
            
          </li>
          <li>
          <Post
              content="hello all i am working on figma trying to design website that
              shows all of my tweets!" date="3/2/2021 "/>
          </li>
        </ul>
        <form>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formButton}>Add to Post</button>
        </form>
      </main>
    </div>
  );
}
